export const FETCH_BALANCE_REQUEST = "balance/FETCH_BALANCE_REQUEST";
export const FETCH_BALANCE_SUCCESS = "balance/FETCH_BALANCE_SUCCESS";
export const FETCH_BALANCE_FAILURE = "balance/FETCH_BALANCE_FAILURE";
