export const FETCH_BUYBACK_ASSET_REQUEST =
  "buyback/FETCH_BUYBACK_ASSET_REQUEST";
export const FETCH_BUYBACK_ASSET_SUCCESS =
  "buyback/FETCH_BUYBACK_ASSET_SUCCESS";
export const FETCH_BUYBACK_ASSET_FAILURE =
  "buyback/FETCH_BUYBACK_ASSET_FAILURE";
