export const FETCH_CLAIMABLE_REQUEST = "claim/FETCH_CLAIMABLE_REQUEST";
export const FETCH_CLAIMABLE_SUCCESS = "claim/FETCH_CLAIMABLE_SUCCESS";
export const FETCH_CLAIMABLE_FAILURE = "claim/FETCH_CLAIMABLE_FAILURE";
