export const DEFAULT_INFORMATION_REQUEST =
  "default/DEFAULT_INFORMATION_REQUEST";
export const DEFAULT_INFORMATION_SUCCESS =
  "default/DEFAULT_INFORMATION_SUCCESS";
export const DEFAULT_INFORMATION_FAILURE =
  "default/DEFAULT_INFORMATION_FAILURE";
