export const FETCH_LIQUIDITY_REQUEST = "liquidity/FETCH_LIQUIDITY_REQUEST";
export const FETCH_LIQUIDITY_SUCCESS = "liquidity/FETCH_LIQUIDITY_SUCCESS";
export const FETCH_LIQUIDITY_FAILURE = "liquidity/FETCH_LIQUIDITY_FAILURE";
