export const FETCH_MY_DEPOSIT_REQUEST = "deposit/FETCH_MY_DEPOSIT_REQUEST";
export const FETCH_MY_DEPOSIT_SUCCESS = "deposit/FETCH_MY_DEPOSIT_SUCCESS";
export const FETCH_MY_DEPOSIT_FAILURE = "deposit/FETCH_MY_DEPOSIT_FAILURE";

export const FETCH_MY_DEPOSIT_AMOUNT_REQUEST =
  "deposit/FETCH_MY_DEPOSIT_AMOUNT_REQUEST";
export const FETCH_MY_DEPOSIT_AMOUNT_SUCCESS =
  "deposit/FETCH_MY_DEPOSIT_AMOUNT_SUCCESS";
export const FETCH_MY_DEPOSIT_AMOUNT_FAILURE =
  "deposit/FETCH_MY_DEPOSIT_AMOUNT_FAILURE";
