export const FETCH_RESERVE_REQUEST = "reserve/FETCH_RESERVE_REQUEST";
export const FETCH_RESERVE_SUCCESS = "reserve/FETCH_RESERVE_SUCCESS";
export const FETCH_RESERVE_FAILURE = "reserve/FETCH_RESERVE_FAILURE";

export const FETCH_ORIGINAL_RESERVE_REQUEST =
  "reserve/FETCH_ORIGINAL_RESERVE_REQUEST";
export const FETCH_ORIGINAL_RESERVE_SUCCESS =
  "reserve/FETCH_ORIGINAL_RESERVE_SUCCESS";
export const FETCH_ORIGINAL_RESERVE_FAILURE =
  "reserve/FETCH_ORIGINAL_RESERVE_FAILURE";
