export const FETCH_SHARE_OF_MY_POOL_REQUEST =
  "share/FETCH_SHARE_OF_MY_POOL_REQUEST";
export const FETCH_SHARE_OF_MY_POOL_SUCCESS =
  "share/FETCH_SHARE_OF_MY_POOL_SUCCESS";
export const FETCH_SHARE_OF_MY_POOL_FAILURE =
  "share/FETCH_SHARE_OF_MY_POOL_FAILURE";
