export const FETCH_SWAP_ESTIMATED_BALANCE_REQUEST =
  "swap/FETCH_SWAP_ESTIMATED_BALANCE_REQUEST";
export const FETCH_SWAP_ESTIMATED_BALANCE_SUCCESS =
  "swap/FETCH_SWAP_ESTIMATED_BALANCE_SUCCESS";
export const FETCH_SWAP_ESTIMATED_BALANCE_FAILURE =
  "swap/FETCH_SWAP_ESTIMATED_BALANCE_FAILURE";
export const FETCH_SWAP_ESTIMATED_BALANCE_CLEANUP =
  "swap/FETCH_SWAP_ESTIMATED_BALANCE_CLEANUP";
