export const CONNECT_WALLET_REQUEST = "wallet/CONNECT_WALLET_REQUEST";
export const CONNECT_WALLET_SUCCESS = "wallet/CONNECT_WALLET_SUCCESS";
export const CONNECT_WALLET_FAILURE = "wallet/CONNECT_WALLET_FAILURE";

export const DISCONNECT_WALLET = "wallet/DISCONNECT_WALLET";

export const ACCOUNTS_CHANGED = "wallet/ACCOUNTS_CHANGED";
