export const SINGLE_DEPOSIT_TRANSACTION_REQUEST =
  "transaction/SINGLE_DEPOSIT_TRANSACTION_REQUEST";
export const SINGLE_DEPOSIT_TRANSACTION_SUCCESS =
  "transaction/SINGLE_DEPOSIT_TRANSACTION_SUCCESS";
export const SINGLE_DEPOSIT_TRANSACTION_FAILURE =
  "transaction/SINGLE_DEPOSIT_TRANSACTION_FAILURE";
export const SINGLE_DEPOSIT_TRANSACTION_CLEANUP =
  "transaction/SINGLE_DEPOSIT_TRANSACTION_CLEANUP";

export const PAIR_DEPOSIT_TRANSACTION_REQUEST =
  "transaction/PAIR_DEPOSIT_TRANSACTION_REQUEST";
export const PAIR_DEPOSIT_TRANSACTION_SUCCESS =
  "transaction/PAIR_DEPOSIT_TRANSACTION_SUCCESS";
export const PAIR_DEPOSIT_TRANSACTION_FAILURE =
  "transaction/PAIR_DEPOSIT_TRANSACTION_FAILURE";
export const PAIR_DEPOSIT_TRANSACTION_CLEANUP =
  "transaction/PAIR_DEPOSIT_TRANSACTION_CLEANUP";

export const PAIR_DEPOSIT_APPROVE1_REQUEST =
  "transaction/PAIR_DEPOSIT_APPROVE1_REQUEST";
export const PAIR_DEPOSIT_APPROVE1_SUCCESS =
  "transaction/PAIR_DEPOSIT_APPROVE1_SUCCESS";
export const PAIR_DEPOSIT_APPROVE1_FAILURE =
  "transaction/PAIR_DEPOSIT_APPROVE1_FAILURE";
export const PAIR_DEPOSIT_APPROVE2_REQUEST =
  "transaction/PAIR_DEPOSIT_APPROVE2_REQUEST";
export const PAIR_DEPOSIT_APPROVE2_SUCCESS =
  "transaction/PAIR_DEPOSIT_APPROVE2_SUCCESS";
export const PAIR_DEPOSIT_APPROVE2_FAILURE =
  "transaction/PAIR_DEPOSIT_APPROVE2_FAILURE";
export const PAIR_DEPOSIT_APPROVE_CLEANUP =
  "transaction/PAIR_DEPOSIT_APPROVE_CLEANUP";
