export const SINGLE_REWARDS_TRANSACTION_REQUEST =
  "transaction/SINGLE_REWARDS_TRANSACTION_REQUEST";
export const SINGLE_REWARDS_TRANSACTION_SUCCESS =
  "transaction/SINGLE_REWARDS_TRANSACTION_SUCCESS";
export const SINGLE_REWARDS_TRANSACTION_FAILURE =
  "transaction/SINGLE_REWARDS_TRANSACTION_FAILURE";
export const SINGLE_REWARDS_TRANSACTION_CLEANUP =
  "transaction/SINGLE_REWARDS_TRANSACTION_CLEANUP";

export const PAIR_REWARDS_TRANSACTION_REQUEST =
  "transaction/PAIR_REWARDS_TRANSACTION_REQUEST";
export const PAIR_REWARDS_TRANSACTION_SUCCESS =
  "transaction/PAIR_REWARDS_TRANSACTION_SUCCESS";
export const PAIR_REWARDS_TRANSACTION_FAILURE =
  "transaction/PAIR_REWARDS_TRANSACTION_FAILURE";
export const PAIR_REWARDS_TRANSACTION_CLEANUP =
  "transaction/PAIR_REWARDS_TRANSACTION_CLEANUP";
