export const SWAP_TRANSACTION_REQUEST = "transaction/SWAP_TRANSACTION_REQUEST";
export const SWAP_TRANSACTION_SUCCESS = "transaction/SWAP_TRANSACTION_SUCCESS";
export const SWAP_TRANSACTION_FAILURE = "transaction/SWAP_TRANSACTION_FAILURE";
export const SWAP_TRANSACTION_CLEANUP = "transaction/SWAP_TRANSACTION_CLEANUP";
