export const SINGLE_WITHDRAW_TRANSACTION_REQUEST =
  "transaction/SINGLE_WITHDRAW_TRANSACTION_REQUEST";
export const SINGLE_WITHDRAW_TRANSACTION_SUCCESS =
  "transaction/SINGLE_WITHDRAW_TRANSACTION_SUCCESS";
export const SINGLE_WITHDRAW_TRANSACTION_FAILURE =
  "transaction/SINGLE_WITHDRAW_TRANSACTION_FAILURE";
export const SINGLE_WITHDRAW_TRANSACTION_CLEANUP =
  "transaction/SINGLE_WITHDRAW_TRANSACTION_CLEANUP";

export const PAIR_WITHDRAW_TRANSACTION_REQUEST =
  "transaction/PAIR_WITHDRAW_TRANSACTION_REQUEST";
export const PAIR_WITHDRAW_TRANSACTION_SUCCESS =
  "transaction/PAIR_WITHDRAW_TRANSACTION_SUCCESS";
export const PAIR_WITHDRAW_TRANSACTION_FAILURE =
  "transaction/PAIR_WITHDRAW_TRANSACTION_FAILURE";
export const PAIR_WITHDRAW_TRANSACTION_CLEANUP =
  "transaction/PAIR_WITHDRAW_TRANSACTION_CLEANUP";

export const PAIR_WITHDRAW_APPROVE_REQUEST =
  "transaction/PAIR_WITHDRAW_APPROVE_REQUEST";
export const PAIR_WITHDRAW_APPROVE_SUCCESS =
  "transaction/PAIR_WITHDRAW_APPROVE_SUCCESS";
export const PAIR_WITHDRAW_APPROVE_FAILURE =
  "transaction/PAIR_WITHDRAW_APPROVE_FAILURE";
export const PAIR_WITHDRAW_APPROVE_CLEANUP =
  "transaction/PAIR_WITHDRAW_APPROVE_CLEANUP";
